import { Router } from 'express';
import * as controller from '../controllers/authController.js';
import { authenticate } from '../middleware/authMiddleware.js';
import { validate } from '../middleware/validateMiddleware.js';
import * as rules from '../validators/index.js';
const router = Router();
router.post('/register', rules.register, validate, controller.register);
router.post('/login', rules.login, validate, controller.login);
router.get('/me', authenticate, controller.me);
router.post('/logout', authenticate, controller.logout);
export default router;
