import { Router } from 'express';
import * as controller from '../controllers/studentController.js';
import { upload } from '../controllers/uploadController.js';
import { authenticate } from '../middleware/authMiddleware.js';
import { authorize } from '../middleware/roleMiddleware.js';
import { validate } from '../middleware/validateMiddleware.js';
import { uploadFile } from '../middleware/uploadMiddleware.js';
import * as rules from '../validators/index.js';
const router = Router();
router.use(authenticate, authorize('student'));
router.get('/profile', controller.getProfile);
router.put('/profile', rules.studentProfile, validate, controller.updateProfile);
router.post('/profile/cv', uploadFile, upload('cv'));
router.post('/profile/picture', uploadFile, upload('image'));
router.get('/analytics', controller.analytics);
router.get('/dashboard', controller.dashboard);
router.get('/followups', controller.listFollowups);
router.post('/followups', rules.followup, validate, controller.createFollowup);
router.delete('/followups/:id', rules.id('id'), validate, controller.removeFollowup);
export default router;
