import {useEffect,useState} from 'react';
import {Link,NavLink,Outlet,useLocation,useNavigate} from 'react-router-dom';
import {LayoutDashboard,BriefcaseBusiness,FileText,Bookmark,Video,CalendarDays,Bell,UserRound,LogOut,Plus,Users,Building2,Menu,X,Sparkles} from 'lucide-react';
import {useAuth} from '../context/AuthContext';
import {useData} from '../context/DataContext';
import {Avatar,Dropdown} from '../components/common/UI';
import {Logo} from './PublicLayout';
const studentLinks=[['Dashboard','dashboard',LayoutDashboard],['Browse Jobs','/jobs',BriefcaseBusiness],['My Applications','applications',FileText],['Saved Jobs','saved-jobs',Bookmark],['Interviews','interviews',Video],['Calendar','calendar',CalendarDays],['Notifications','notifications',Bell],['Profile','profile',UserRound]];
const providerLinks=[['Dashboard','dashboard',LayoutDashboard],['Job Postings','jobs',BriefcaseBusiness],['Create Job','jobs/new',Plus],['Applicants','applicants',Users],['Interviews','interviews',Video],['Notifications','notifications',Bell],['Company Profile','profile',Building2]];
export default function DashboardLayout({role}){const {user,logout}=useAuth();const data=useData();const [open,setOpen]=useState(false);const location=useLocation();const navigate=useNavigate();const links=role==='student'?studentLinks:providerLinks;const unread=data.notifications.filter(n=>n.userId===user.id&&!n.read).length;const current=links.find(([,path])=>location.pathname===`/${role}/${path}`)?.[0]||'Workspace';useEffect(()=>setOpen(false),[location.pathname]);useEffect(()=>{const close=e=>{if(e.key==='Escape')setOpen(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);const signOut=()=>{logout();navigate('/');};return <div className="dashboard-shell"><a href="#main-content" className="skip-link">Skip to content</a>{open&&<button className="drawer-shade" aria-label="Close sidebar" onClick={()=>setOpen(false)}/>}<aside className={`sidebar ${open?'open':''}`} aria-label={`${role} navigation`}><Logo/><button className="icon-btn sidebar-close" aria-label="Close sidebar" onClick={()=>setOpen(false)}><X size={16}/></button><div className="workspace-label">{role==='student'?'YOUR CAREER SPACE':'EMPLOYER WORKSPACE'}</div><nav className="sidebar-nav">{links.map(([label,path,Icon])=><NavLink end to={path.startsWith('/')?path:`/${role}/${path}`} key={path}><Icon size={18}/>{label}{path==='notifications'&&unread>0&&<span className="sidebar-count">{unread}</span>}</NavLink>)}</nav><div className="sidebar-bottom"><div className="sidebar-note"><Sparkles size={20}/><h3>{role==='student'?'Small steps. Big futures.':'Great teams start here.'}</h3><p>{role==='student'?'Your next opportunity could be one application away.':'Find the potential that moves your team forward.'}</p></div><button className="sidebar-logout" onClick={signOut}><LogOut size={17}/>Log out</button><Link to={`/${role}/profile`} className="sidebar-user"><Avatar name={user.name} src={user.picture}/><div><strong>{user.name}</strong><small>{role==='student'?'Student account':'Employer account'}</small></div></Link></div></aside><div className="dashboard-main"><header className="dashboard-topbar"><div className="inline-row"><button className="icon-btn mobile-toggle" aria-expanded={open} aria-label="Open sidebar" onClick={()=>setOpen(true)}><Menu size={20}/></button><div className="breadcrumb">My workspace <span>/ {current}</span></div></div><div className="topbar-actions"><span className="demo-indicator">DEMO WORKSPACE</span><Link to={`/${role}/notifications`} className="icon-btn notification-dot" aria-label={`Notifications, ${unread} unread`}><Bell size={18}/>{unread>0&&<i/>}</Link><Dropdown label={<Avatar name={user.name} src={user.picture}/>}><Link to={`/${role}/profile`}>Edit profile</Link><Link to="/">Visit homepage</Link><button className="btn btn-ghost" onClick={signOut}>Log out</button></Dropdown></div></header><main id="main-content" className="dashboard-content"><Outlet/></main></div></div>;}
